# Generated by Django 4.0.1 on 2022-01-17 18:47

from django.db import migrations, models
import ishop.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=ishop.helpers.UploadTo('category')),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=ishop.helpers.UploadTo('category')),
        ),
    ]
