# Generated by Django 4.0.1 on 2022-01-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Yangi'), (0, 'Qabul qilingan'), (0, 'Qaytarilgan'), (0, "Yo'lda"), (0, 'Yetkazib berilgan'), (0, 'Yopilgan')], default=0),
        ),
    ]
